kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adminbinding
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo835
  apiGroup: ""
roleRef:
  kind: Role
  name: admin
  apiGroup: ""