kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: final
  name: pod-writer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list","get","watch","update"]
- apiGroups: ["extensions","apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch","update"]