apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
  labels:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/component: simple-webapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
      app.kubernetes.io/component: simple-webapp
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
        app.kubernetes.io/component: simple-webapp
    spec:
      containers:
      - name: example-app
        image: 792299080144.dkr.ecr.us-east-1.amazonaws.com/clo835:v1.1
       
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
             name: app-secret
          - configMapRef: 
             name: webapp-config