apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
  labels:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/component: simple-webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 81
  selector:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/component: simple-webapp