apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
  labels:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/component: simple-webapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
      app.kubernetes.io/component: simple-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
        app.kubernetes.io/component: simple-webapp
    spec:
      containers:
      - name: simple-webapp
        image: 792299080144.dkr.ecr.us-east-1.amazonaws.com/clo835:latest
        volumeMounts:
        - name: app-secret-volume
          mountPath: "/opt/app-secret-volumes"
          readOnly: true
        ports:
        - containerPort: 81
        envFrom:
          - secretRef:
              name: app-secret
        env:
          - name: IMAGE_URL_PATH
            valueFrom:
              configMapKeyRef: 
                name: webapp-config
                key: IMAGE_URL_PATH
          - name: IMAGE_URL_S3
            valueFrom:
              configMapKeyRef:
                name: webapp-config
                key: IMAGE_URL_S3
      volumes:
      - name: app-secret-volume
        secret:
          secretName: app-secret